[2022-12-20 02:55:03,075: INFO/MainProcess] beat: Starting...
[2022-12-20 02:55:03,797: WARNING/MainProcess] /usr/local/lib/python3.10/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-12-20 02:55:03,812: WARNING/MainProcess] Please run `celery upgrade settings path/to/settings.py` to avoid these warnings and to allow a smoother upgrade to Celery 6.0.
[2022-12-20 02:55:04,670: INFO/MainProcess] Connected to redis://redis:6379/0
[2022-12-20 02:55:04,679: INFO/MainProcess] mingle: searching for neighbors
[2022-12-20 02:55:05,694: INFO/MainProcess] mingle: all alone
[2022-12-20 02:55:05,719: INFO/MainProcess] celery@c99243bdbbf3 ready.
[2022-12-20 02:55:16,437: INFO/MainProcess] Events of group {task} enabled by remote.
[2022-12-20 02:58:10,120: INFO/MainProcess] Task project.users.tasks.sample_task[d3932376-4e54-4a79-b354-81bce32e878f] received
[2022-12-20 02:58:10,141: ERROR/ForkPoolWorker-7] Task project.users.tasks.sample_task[d3932376-4e54-4a79-b354-81bce32e878f] raised unexpected: Exception('random processing error')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/project/celery_utils.py", line 32, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/app/project/users/tasks.py", line 29, in sample_task
    api_call(email)
  File "/app/project/users/views.py", line 29, in api_call
    raise Exception('random processing error')
Exception: random processing error
[2022-12-20 02:58:18,155: INFO/MainProcess] Task project.users.tasks.sample_task[cdcaccbe-c13f-4e4f-beaf-551b651c0fb2] received
[2022-12-20 02:58:24,716: INFO/ForkPoolWorker-7] Task project.users.tasks.sample_task[cdcaccbe-c13f-4e4f-beaf-551b651c0fb2] succeeded in 6.555419299998903s: None
[2022-12-20 03:01:20,293: INFO/MainProcess] Task project.users.tasks.sample_task[15aa0ce8-3b1f-41ee-8151-d442c23cc8cf] received
[2022-12-20 03:01:27,097: INFO/ForkPoolWorker-7] Task project.users.tasks.sample_task[15aa0ce8-3b1f-41ee-8151-d442c23cc8cf] succeeded in 6.79899569999543s: None
